export interface BanglaSurahData {
  number: number;
  banglaName: string;
  banglaMeaning: string;
  banglaPronunciation: string;
}

export const BANGLA_SURAH_MAP: Record<number, BanglaSurahData> = {
  1: { number: 1, banglaName: "আল-ফাতিহা", banglaMeaning: "সূচনা", banglaPronunciation: "Al-Fatihah" },
  2: { number: 2, banglaName: "আল-বাকারা", banglaMeaning: "বকনা বাছুর", banglaPronunciation: "Al-Baqarah" },
  3: { number: 3, banglaName: "আল-ইমরান", banglaMeaning: "ইমরানের পরিবার", banglaPronunciation: "Ali 'Imran" },
  4: { number: 4, banglaName: "আন-নিসা", banglaMeaning: "নারী", banglaPronunciation: "An-Nisa" },
  5: { number: 5, banglaName: "আল-মায়িদাহ", banglaMeaning: "দস্তরখান", banglaPronunciation: "Al-Ma'idah" },
  6: { number: 6, banglaName: "আল-আন'আম", banglaMeaning: "গৃহপালিত পশু", banglaPronunciation: "Al-An'am" },
  7: { number: 7, banglaName: "আল-আ'রাফ", banglaMeaning: "সীমান্ত প্রাচীর", banglaPronunciation: "Al-A'raf" },
  8: { number: 8, banglaName: "আল-আনফাল", banglaMeaning: "যুদ্ধলব্ধ সম্পদ", banglaPronunciation: "Al-Anfal" },
  9: { number: 9, banglaName: "আত-তাওবাহ", banglaMeaning: "অনুতাপ", banglaPronunciation: "At-Tawbah" },
  10: { number: 10, banglaName: "ইউনুস", banglaMeaning: "ইউনুস (আঃ)", banglaPronunciation: "Yunus" },
  11: { number: 11, banglaName: "হুদ", banglaMeaning: "হুদ (আঃ)", banglaPronunciation: "Hud" },
  12: { number: 12, banglaName: "ইউসুফ", banglaMeaning: "ইউসুফ (আঃ)", banglaPronunciation: "Yusuf" },
  13: { number: 13, banglaName: "আর-রাদ", banglaMeaning: "বজ্রপাত", banglaPronunciation: "Ar-Ra'd" },
  14: { number: 14, banglaName: "ইব্রাহিম", banglaMeaning: "ইব্রাহিম (আঃ)", banglaPronunciation: "Ibrahim" },
  15: { number: 15, banglaName: "আল-হিজর", banglaMeaning: "পাথুরে পাহাড়", banglaPronunciation: "Al-Hijr" },
  16: { number: 16, banglaName: "আন-নাহল", banglaMeaning: "মৌমাছি", banglaPronunciation: "An-Nahl" },
  17: { number: 17, banglaName: "আল-ইসরা", banglaMeaning: "বনী ইসরাঈল", banglaPronunciation: "Al-Isra" },
  18: { number: 18, banglaName: "আল-কাহফ", banglaMeaning: "গুহা", banglaPronunciation: "Al-Kahf" },
  19: { number: 19, banglaName: "মারইয়াম", banglaMeaning: "মারইয়াম", banglaPronunciation: "Maryam" },
  20: { number: 20, banglaName: "ত্বোয়া-হা", banglaMeaning: "ত্বোয়া-হা", banglaPronunciation: "Ta-Ha" },
  21: { number: 21, banglaName: "আল-আম্বিয়া", banglaMeaning: "নবীগণ", banglaPronunciation: "Al-Anbiya" },
  22: { number: 22, banglaName: "আল-হাজ্জ", banglaMeaning: "হজ্জ", banglaPronunciation: "Al-Hajj" },
  23: { number: 23, banglaName: "আল-মুমিনুন", banglaMeaning: "বিশ্বাসী দল", banglaPronunciation: "Al-Mu'minun" },
  24: { number: 24, banglaName: "আন-নূর", banglaMeaning: "জ্যোতি", banglaPronunciation: "An-Nur" },
  25: { number: 25, banglaName: "আল-ফুরকান", banglaMeaning: "মানদণ্ড", banglaPronunciation: "Al-Furqan" },
  26: { number: 26, banglaName: "আশ-শু'আরা", banglaMeaning: "কবিগণ", banglaPronunciation: "Ash-Shu'ara" },
  27: { number: 27, banglaName: "আন-নামল", banglaMeaning: "পিপীলিকা", banglaPronunciation: "An-Naml" },
  28: { number: 28, banglaName: "আল-কাসাস", banglaMeaning: "কাহিনী", banglaPronunciation: "Al-Qasas" },
  29: { number: 29, banglaName: "আল-আনকাবুত", banglaMeaning: "মাকড়সা", banglaPronunciation: "Al-'Ankabut" },
  30: { number: 30, banglaName: "আর-রূম", banglaMeaning: "রোমান জাতি", banglaPronunciation: "Ar-Rum" },
  31: { number: 31, banglaName: "লুকমান", banglaMeaning: "হাকীম লুকমান", banglaPronunciation: "Luqman" },
  32: { number: 32, banglaName: "আস-সাজদাহ", banglaMeaning: "প্রণিপাত / সিজদাহ", banglaPronunciation: "As-Sajdah" },
  33: { number: 33, banglaName: "আল-আহযাব", banglaMeaning: "সম্মিলিত দল", banglaPronunciation: "Al-Ahzab" },
  34: { number: 34, banglaName: "সাবা", banglaMeaning: "সাবার অধিবাসী", banglaPronunciation: "Saba'" },
  35: { number: 35, banglaName: "ফাতির", banglaMeaning: "আদি স্রষ্টা", banglaPronunciation: "Fatir" },
  36: { number: 36, banglaName: "ইয়া-সীন", banglaMeaning: "ইয়া-সীন", banglaPronunciation: "Ya-Sin" },
  37: { number: 37, banglaName: "আস-সাফফাত", banglaMeaning: "সারিবদ্ধভাবে দাঁড়ানো", banglaPronunciation: "As-Saffat" },
  38: { number: 38, banglaName: "স্বাদ", banglaMeaning: "স্বাদ আরবি বর্ণ", banglaPronunciation: "Sad" },
  39: { number: 39, banglaName: "আয-যুমার", banglaMeaning: "জনতা / দলসমূহ", banglaPronunciation: "Az-Zumar" },
  40: { number: 40, banglaName: "গাফির", banglaMeaning: "মুমিন / ক্ষমাশীল", banglaPronunciation: "Ghafir" },
  41: { number: 41, banglaName: "ফুসসিলাত", banglaMeaning: "সুস্পষ্ট বিবরণ", banglaPronunciation: "Fussilat" },
  42: { number: 42, banglaName: "আশ-শূরা", banglaMeaning: "পরামর্শসভা", banglaPronunciation: "Ash-Shura" },
  43: { number: 43, banglaName: "আয-যুখরুফ", banglaMeaning: "স্বর্ণালংকার", banglaPronunciation: "Az-Zukhruf" },
  44: { number: 44, banglaName: "আদ-দুখান", banglaMeaning: "ধোঁয়া", banglaPronunciation: "Ad-Dukhan" },
  45: { number: 45, banglaName: "আল-জাথিয়াহ", banglaMeaning: "নতজানু", banglaPronunciation: "Al-Jathiyah" },
  46: { number: 46, banglaName: "আল-আহকাফ", banglaMeaning: "বালিয়াড়ি পাহাড়", banglaPronunciation: "Al-Ahqaf" },
  47: { number: 47, banglaName: "মুহাম্মদ", banglaMeaning: "মুহাম্মদ (সাঃ)", banglaPronunciation: "Muhammad" },
  48: { number: 48, banglaName: "আল-ফাতাহ", banglaMeaning: "বিজয়", banglaPronunciation: "Al-Fath" },
  49: { number: 49, banglaName: "আল-হুজুরাত", banglaMeaning: "কক্ষসমূহ", banglaPronunciation: "Al-Hujurat" },
  50: { number: 50, banglaName: "ক্বাফ", banglaMeaning: "ক্বাফ আরবি বর্ণ", banglaPronunciation: "Qaf" },
  51: { number: 51, banglaName: "আয-যারিয়াত", banglaMeaning: "বিক্ষেপকারী বাতাস", banglaPronunciation: "Adh-Dhariyat" },
  52: { number: 52, banglaName: "আত-তূর", banglaMeaning: "তূর পর্বত", banglaPronunciation: "At-Tur" },
  53: { number: 53, banglaName: "আন-নাজম", banglaMeaning: "নক্ষত্র", banglaPronunciation: "An-Najm" },
  54: { number: 54, banglaName: "আল-কামার", banglaMeaning: "চন্দ্র", banglaPronunciation: "Al-Qamar" },
  55: { number: 55, banglaName: "আর-রাহমান", banglaMeaning: "পরম করুণাময়", banglaPronunciation: "Ar-Rahman" },
  56: { number: 56, banglaName: "আল-ওয়াকি'আহ", banglaMeaning: "কেয়ামত / ঘটনা", banglaPronunciation: "Al-Waqi'ah" },
  57: { number: 57, banglaName: "আল-হাদীদ", banglaMeaning: "লোহা", banglaPronunciation: "Al-Hadid" },
  58: { number: 58, banglaName: "আল-মুজাদিলাহ", banglaMeaning: "তর্কধারিণী নারী", banglaPronunciation: "Al-Mujadilah" },
  59: { number: 59, banglaName: "আল-হাশর", banglaMeaning: "হাশর / মহাসমাবেশ", banglaPronunciation: "Al-Hashr" },
  60: { number: 60, banglaName: "আল-মুমতাহানাহ", banglaMeaning: "পরীক্ষিত রমণী", banglaPronunciation: "Al-Mumtahanah" },
  61: { number: 61, banglaName: "আস-সাফ", banglaMeaning: "সৈন্যদল", banglaPronunciation: "As-Saff" },
  62: { number: 62, banglaName: "আল-জুমু'আহ", banglaMeaning: "শুক্রবার", banglaPronunciation: "Al-Jumu'ah" },
  63: { number: 63, banglaName: "আল-মুনাফিকুন", banglaMeaning: "কপটচারী দল", banglaPronunciation: "Al-Munafiqun" },
  64: { number: 64, banglaName: "আত-তাগাবুন", banglaMeaning: "ক্ষতি ও লাভ", banglaPronunciation: "At-Taghabun" },
  65: { number: 65, banglaName: "আত-তালাক", banglaMeaning: "বিবাহ বিচ্ছেদ", banglaPronunciation: "At-Talaq" },
  66: { number: 66, banglaName: "আত-তাহরীম", banglaMeaning: "হারাম বা নিষিদ্ধকরণ", banglaPronunciation: "At-Tahrim" },
  67: { number: 67, banglaName: "আল-মূলক", banglaMeaning: "সার্বভৌম কর্তৃত্ব", banglaPronunciation: "Al-Mulk" },
  68: { number: 68, banglaName: "আল-কালাম", banglaMeaning: "লেখনী / কলম", banglaPronunciation: "Al-Qalam" },
  69: { number: 69, banglaName: "আল-হাক্কাহ", banglaMeaning: "অনিবার্য মহাসত্য", banglaPronunciation: "Al-Haqqah" },
  70: { number: 70, banglaName: "আল-মা'আরিজ", banglaMeaning: "ঊর্ধ্বগমনের পথ", banglaPronunciation: "Al-Ma'arij" },
  71: { number: 71, banglaName: "নূহ", banglaMeaning: "নূহ (আঃ)", banglaPronunciation: "Nuh" },
  72: { number: 72, banglaName: "আল-জ্বিন", banglaMeaning: "জ্বিন সম্প্রদায়", banglaPronunciation: "Al-Jinn" },
  73: { number: 73, banglaName: "আল-মুযযাম্মিল", banglaMeaning: "চাদর আবৃত", banglaPronunciation: "Al-Muzzammil" },
  74: { number: 74, banglaName: "আল-মুদ্দাসসির", banglaMeaning: "পোশাক পরিহিত", banglaPronunciation: "Al-Muddaththir" },
  75: { number: 75, banglaName: "আল-কিয়ামাহ", banglaMeaning: "কেয়ামত বা উত্থান দিন", banglaPronunciation: "Al-Qiyamah" },
  76: { number: 76, banglaName: "আল-ইনসান", banglaMeaning: "মানব জাতি", banglaPronunciation: "Al-Insan" },
  77: { number: 77, banglaName: "আল-মুরসালাত", banglaMeaning: "প্রেরিত বায়ুপ্রবাহ", banglaPronunciation: "Al-Mursalat" },
  78: { number: 78, banglaName: "আন-নাবা", banglaMeaning: "মহাসংবাদ", banglaPronunciation: "An-Naba" },
  79: { number: 79, banglaName: "আন-নাযি'আত", banglaMeaning: "প্রাণ হরণকারী ফিরিশতা", banglaPronunciation: "An-Nazi'at" },
  80: { number: 80, banglaName: "আবাসা", banglaMeaning: "তিনি ভ্রুকুটি করলেন", banglaPronunciation: "Abasa" },
  81: { number: 81, banglaName: "আত-তাকভীর", banglaMeaning: "কুঁচকানো / গুটিয়ে নেওয়া", banglaPronunciation: "At-Takwir" },
  82: { number: 82, banglaName: "আল-ইনফিতার", banglaMeaning: "বিদীর্ণ হওয়া", banglaPronunciation: "Al-Infitar" },
  83: { number: 83, banglaName: "আল-মুতাফফিফীন", banglaMeaning: "পরিমাপে ঠকানো ব্যক্তিরা", banglaPronunciation: "Al-Mutaffifin" },
  84: { number: 84, banglaName: "আল-ইনশিকাক", banglaMeaning: "ফেটে যাওয়া", banglaPronunciation: "Al-Inshiqaq" },
  85: { number: 85, banglaName: "আল-বুরুজ", banglaMeaning: "নক্ষত্রপুঞ্জ", banglaPronunciation: "Al-Buruj" },
  86: { number: 86, banglaName: "আত-তারিক", banglaMeaning: "রাতের নক্ষত্র", banglaPronunciation: "At-Tariq" },
  87: { number: 87, banglaName: "আল-আ'la", banglaMeaning: "সর্বোচ্চ সত্তা", banglaPronunciation: "Al-A'la" },
  88: { number: 88, banglaName: "আল-গাশিয়াহ", banglaMeaning: "অভিভূতকারী ঘটনা", banglaPronunciation: "Al-Ghashiyah" },
  89: { number: 89, banglaName: "আল-ফাজর", banglaMeaning: "ভোরবেলা", banglaPronunciation: "Al-Fajr" },
  90: { number: 90, banglaName: "আল-বালাদ", banglaMeaning: "জনপদ / শহর", banglaPronunciation: "Al-Balad" },
  91: { number: 91, banglaName: "আশ-শামস", banglaMeaning: "সূর্য", banglaPronunciation: "Ash-Shams" },
  92: { number: 92, banglaName: "আল-লাইল", banglaMeaning: "রাত্রি", banglaPronunciation: "Al-Layl" },
  93: { number: 93, banglaName: "আদ-দুহা", banglaMeaning: "পূর্বাহ্নের রোদ", banglaPronunciation: "Ad-Duha" },
  94: { number: 94, banglaName: "আশ-শারহ", banglaMeaning: "বক্ষ প্রসারণ করা", banglaPronunciation: "Ash-Sharh" },
  95: { number: 95, banglaName: "আত-তীন", banglaMeaning: "ডুমুর ফল", banglaPronunciation: "At-Tin" },
  96: { number: 96, banglaName: "আল-আলাক", banglaMeaning: "রক্তপিণ্ড", banglaPronunciation: "Al-'Alaq" },
  97: { number: 97, banglaName: "আল-কদর", banglaMeaning: "সম্মানিত রজনী", banglaPronunciation: "Al-Qadr" },
  98: { number: 98, banglaName: "আল-বাইয়িনাহ", banglaMeaning: "সুস্পষ্ট প্রমাণ", banglaPronunciation: "Al-Bayyinah" },
  99: { number: 99, banglaName: "আয-যালযালাh", banglaMeaning: "ভূমিকম্প", banglaPronunciation: "Az-Zalzalah" },
  100: { number: 100, banglaName: "আল-আদিয়াত", banglaMeaning: "অভিযানকারী অশ্বসমূহ", banglaPronunciation: "Al-'Adiyat" },
  101: { number: 101, banglaName: "আল-কারিয়াহ", banglaMeaning: "মহাসংকটকারী আঘাত", banglaPronunciation: "Al-Qari'ah" },
  102: { number: 102, banglaName: "আত-তাকাসুর", banglaMeaning: "প্রাচুর্যের লোভ", banglaPronunciation: "At-Takathur" },
  103: { number: 103, banglaName: "আল-আসর", banglaMeaning: "মহাকাল / বিকেল", banglaPronunciation: "Al-'Asr" },
  104: { number: 104, banglaName: "আল-হুমাযাহ", banglaMeaning: "গীবতকারী ব্যক্তি", banglaPronunciation: "Al-Humazah" },
  105: { number: 105, banglaName: "আল-ফীল", banglaMeaning: "হাতি", banglaPronunciation: "Al-Fil" },
  106: { number: 106, banglaName: "কুরাইশ", banglaMeaning: "কুরাইশ গোত্র", banglaPronunciation: "Quraysh" },
  107: { number: 107, banglaName: "আল-মা'উন", banglaMeaning: "নিত্যপ্রয়োজনীয় সাহায্য", banglaPronunciation: "Al-Ma'un" },
  108: { number: 108, banglaName: "আল-কাওসার", banglaMeaning: "প্রাচুর্যের প্রস্রবণ", banglaPronunciation: "Al-Kawthar" },
  109: { number: 109, banglaName: "আল-কাফিরুন", banglaMeaning: "কাফির সম্প্রদায়", banglaPronunciation: "Al-Kafirun" },
  110: { number: 110, banglaName: "আন-নাসর", banglaMeaning: "স্বর্গীয় সাহায্য", banglaPronunciation: "An-Nasr" },
  111: { number: 111, banglaName: "আল-মাসাদ", banglaMeaning: "খেজুরগাছের পাকানো কাছি", banglaPronunciation: "Al-Masad" },
  112: { number: 112, banglaName: "আল-ইখলাস", banglaMeaning: "নিষ্ঠা / একত্ববাদ", banglaPronunciation: "Al-Ikhlas" },
  113: { number: 113, banglaName: "আল-ফালাক", banglaMeaning: "ঊষাকাল", banglaPronunciation: "Al-Falaq" },
  114: { number: 114, banglaName: "আন-নাস", banglaMeaning: "মানবজাতি", banglaPronunciation: "An-Nas" }
};

export const getBanglaSurahData = (number: number): BanglaSurahData => {
  return BANGLA_SURAH_MAP[number] || {
    number,
    banglaName: "সূরা",
    banglaMeaning: "অনুবাদ পাওয়া যায়নি",
    banglaPronunciation: "Surah"
  };
};
